Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Not Found: /favicon.ico
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Enter Valid Credentials
Enter Valid Credentials
Successfuly login
Successfuly login
Successfuly login
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Enter Valid Credentials
Successfuly login
Watching for file changes with StatReloader
Successfuly login
